version: '3.9'
services:
  database:
    image: mysql:8
    container_name: app-database
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    restart: always
  backend:
    build: ./back-end
    container_name: app-backend
    platform: linux/x86_64
    volumes:
      - ./back-end:/app/backend
    ports:
      - 3001:3001
    depends_on:
      database:
        condition: service_healthy
    environment:
      - HOSTNAME=database
      - MYSQL_HOST=database
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  frontend:
    build: ./front-end
    container_name: app-frontend
    platform: linux/x86_64
    volumes:
      - ./front-end:/app/frontend
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy

